#!/bin/bash
ENV=$1
if [ "${ENV}" = 'prod' ]; then
    echo "Syncing to muzzammil.us"
    aws s3 sync . s3://muzzammil.us --exclude=.git/* \
        --exclude 'xxx/*'
else
    echo "Syncing to staging.muzzammil.us"
    aws s3 sync . s3://staging.muzzammil.us --exclude=.git/* \
        --exclude 'xxx/*'
fi
